### ISSUE TITLE
Git push by SSH authentication, Permission denied

### ISSUE THREAD

**Issue by RichardFreeman** [drone-plugins/drone-git-push#9]
I want to deploy the code after it got the test to pass, but I got a error that's SSH authentication permission denied, I added root user public key in Drone host server to SSH Git target server's authentication file. where did I do wrong?

**Comment by RichardFreeman** [comment]
Isn't it the same public key that drone-git-push and drone-git used in Drone host server ?

**Comment by tboerger** [comment]
No, you have to copy the SSH key from the repository page. In drone every project got a custom public key which you can see on the settings page
